syntax = "proto3";

package bully;

option go_package = "github.com/oyavri/pi-bully/gen/bully";

// --- Election ---
message ElectionRequest {
  uint64 from_id = 1;
  uint64 term = 2;
  string grpc_addr = 3;
}

message ElectionResponse {
  bool ok = 1;
  uint64 term = 2;
}

message CoordinatorRequest {
  uint64 leader_id = 1;
  uint64 term = 2;
}

message CoordinatorResponse {}

service ElectionService {
  rpc StartElection(ElectionRequest) returns (ElectionResponse);
  rpc AnnounceLeader(CoordinatorRequest) returns (CoordinatorResponse);
}

// --- Worker ---
service WorkerService {
  rpc AssignTask(AssignTaskRequest) returns (AssignTaskResponse);
}

message AssignTaskRequest {
  string task_id = 1;
  string executable_uri = 2;
  string input_uri = 3;
  string output_uri = 4;
  repeated string args = 5;
}

message AssignTaskResponse {
  bool accepted = 1;
}

message RenewLeaseRequest {
  string task_id = 1;
  uint64 worker_id = 2;
}

message RenewLeaseResponse {}

// --- Scheduler ---
service SchedulerService {
  rpc RenewLease(RenewLeaseRequest) returns (RenewLeaseResponse);
  rpc ReportResult(ReportResultRequest) returns (ReportResultResponse);
}

enum TaskOutcome {
  TASK_OUTCOME_UNSPECIFIED = 0; // there should be no default status behavior
  SUCCESS = 1;
  FAILED = 2;
}

message ReportResultRequest {
  string task_id = 1;
  uint64 worker_id = 2;
  TaskOutcome outcome = 3;
  string error = 4;
}

message ReportResultResponse {}
