// Code generated by MockGen. DO NOT EDIT.
// Source: task/task.go
//
// Generated by this command:
//
//	mockgen -source=task/task.go -destination=task/mocks/mock_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	task "github.com/oyavri/pi-bully/task"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ClaimQueued mocks base method.
func (m *MockStore) ClaimQueued(ctx context.Context, workerID string, batchSize int) ([]task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimQueued", ctx, workerID, batchSize)
	ret0, _ := ret[0].([]task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimQueued indicates an expected call of ClaimQueued.
func (mr *MockStoreMockRecorder) ClaimQueued(ctx, workerID, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimQueued", reflect.TypeOf((*MockStore)(nil).ClaimQueued), ctx, workerID, batchSize)
}

// MarkCompleted mocks base method.
func (m *MockStore) MarkCompleted(ctx context.Context, taskID uuid.UUID, workerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCompleted", ctx, taskID, workerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCompleted indicates an expected call of MarkCompleted.
func (mr *MockStoreMockRecorder) MarkCompleted(ctx, taskID, workerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCompleted", reflect.TypeOf((*MockStore)(nil).MarkCompleted), ctx, taskID, workerID)
}

// MarkFailed mocks base method.
func (m *MockStore) MarkFailed(ctx context.Context, taskID uuid.UUID, workerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, taskID, workerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockStoreMockRecorder) MarkFailed(ctx, taskID, workerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockStore)(nil).MarkFailed), ctx, taskID, workerID)
}

// MarkRunning mocks base method.
func (m *MockStore) MarkRunning(ctx context.Context, taskID uuid.UUID, workerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRunning", ctx, taskID, workerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRunning indicates an expected call of MarkRunning.
func (mr *MockStoreMockRecorder) MarkRunning(ctx, taskID, workerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRunning", reflect.TypeOf((*MockStore)(nil).MarkRunning), ctx, taskID, workerID)
}
